CookingIndex:
    pattern:  /
    defaults: { _controller: Rap2hCookingBundle:Cooking:index }

CookingAbout:
    pattern:  /about
    defaults: { _controller: Rap2hCookingBundle:Cooking:about }


CookingStart:
    pattern:  /start
    defaults: { _controller: Rap2hCookingBundle:Cooking:start }

CookingAddRecipeItem:
    pattern:  /add/{recipeItemId}
    defaults: { _controller: Rap2hCookingBundle:Cooking:addRecipeStep }
    requirements:
        recipeItemId: \d+

CookingResetRecipe:
    pattern:  /reset/
    defaults: { _controller: Rap2hCookingBundle:Cooking:resetRecipe }


# Administration

CookingAdminAddRecipe:
    pattern:  /adminAddRecipe/
    defaults: { _controller: Rap2hCookingBundle:Admin:addRecipe}

CookingAdminJoinRecipeSteps:
    pattern:  /adminJoinRecipeSteps/
    defaults: { _controller: Rap2hCookingBundle:Admin:joinRecipeSteps}

CookingAdminManageRecipes:
    pattern:  /adminManageRecipes/
    defaults: { _controller: Rap2hCookingBundle:Admin:manageRecipes}

CookingAdminDeleteRecipe:
    pattern:  /adminDeleteRecipe/{recipeId}
    defaults: { _controller: Rap2hCookingBundle:Admin:deleteRecipe}
    requirements:
        recipeItemId: \d+