CookingIndex:
    pattern:  /
    defaults: { _controller: Rap2hCookingBundle:Cooking:index }

CookingAbout:
    pattern:  /about
    defaults: { _controller: Rap2hCookingBundle:Cooking:about }


CookingStart:
    pattern:  /start
    defaults: { _controller: Rap2hCookingBundle:Cooking:start }

CookingAddRecipeItem:
    pattern:  /add/{recipeItemId}
    defaults: { _controller: Rap2hCookingBundle:Cooking:addRecipeItem }
    requirements:
        # recipeItemId: \d+

CookingResetRecipe:
    pattern:  /reset/
    defaults: { _controller: Rap2hCookingBundle:Cooking:resetRecipe }

CookingAdminAddRandomRecipeItem:
    pattern:  /adminAddRandomItem/{addChilds}
    defaults: { _controller: Rap2hCookingBundle:Cooking:adminAddRandomItem, addChilds: false }

CookingAdminAddRecipe:
    pattern:  /adminAddRecipe/
    defaults: { _controller: Rap2hCookingBundle:Cooking:adminAddRecipe}
