parameters:
    rap2h_cooking.cooking_session.class: Rap2h\CookingBundle\CookingSession\CookingSession

services:
    rap2h_cooking.cooking_session:
        class: %rap2h_cooking.cooking_session.class%
        arguments: [@session]
#       arguments: [@service_id, "plain_value", %parameter%]
