<?php

namespace Rap2h\CookingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RecipeStepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeStepRepository extends EntityRepository
{
}
